### ISSUE TITLE
error while excuting BPSK and transfering large file 

### ISSUE THREAD

**Issue by AbdoRaheel** [duggabe/gr-control#10]
Hi all
While sending a file bigger than 148 KB , This error occurs "QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
thread_body_wrapper :error: ERROR thread[thread-per-block[0]: <block EPB: File Source to Tagged Stream(5)>]: IndexError: index 15 is out of bounds for axis 0 with size 15

At:
  /home/raheel/gr-control/Transmitters/pkt_xmt_epy_block_0.py(109): work
  /usr/lib/python3/dist-packages/gnuradio/gr/gateway.py(199): handle_general_work"

**Comment by duggabe** [comment]
First of all, this project is a "proof of concept" design. There are several things which would need to be done to make a "production-quality" system. Currently, even a single bit error will cause an entire packet of data to be discarded, regardless of the size of the file.

However, your particular problem may be due to storage limits in your file system. It's hard to tell without more information.

To make a more robust system, I would consider doing one of the following:

- add Forward Error Correction (FEC) code
- use packet numbering and feedback to verify each packet - similar to TCP
