### ISSUE TITLE
fix for NFM_rcv.grc file

### ISSUE THREAD

**Issue by tempacct791** [duggabe/gr-control#2]
File: https://github.com/duggabe/gr-control/blob/maint-3.8/Receivers/NFM_rcv.grc
Line 42:     low_cutoff_freq: '-3000'
Need to replace '-3000' with '300'
Also for all other branches

**Comment by duggabe** [comment]
I think you are confusing channel filtering with audio filtering. The filter I used could be replaced with a Low Pass Filter and it could use Real taps instead of Complex taps. That would actually simplify it. This was a carry-over from a WBFM stereo flowgraph. You are welcome to fork the repo and make your own version.

For additional information, see https://pysdr.org/content/filters.html#

**Comment by tempacct791** [comment]
thanks for your reply. my original post didn't come out right. i just started learning gnuradio, and one of the very first tutorials links to your github files, https://wiki.gnuradio.org/index.php/Simulation_example:_Narrowband_FM_transceiver, but GRC wouldn't run the file in its current state. so i thought i might be able to help the next newbie.
